### PR TITLE
Import ICS files

### PR DESCRIPTION
**Pull request by in0rdr**
This is a WIP to implement https://github.com/in0rdr/diary/issues/76

Done:
- Read user input on keypress (`i`, for "import")
- Read first `VEVENT DESCRIPTION` from a file specified by the user

To be done:
- [x] Read multiple `VEVENTS`
- [x] Read `DTSTART` date
- [x] NULL `DESCRIPTION` segfault
- [x] fix repeated import
  * double free or corruption (!prev)
  * realloc(): invalid pointer
- [x] User confirmation for writing to text files in the diary dir
- [x] Write events to text files
- [x] Cleanup `extract_ical_field` and check changes don't mess with #75
- [x] Add loading character to report progress
- [ ] Add export to ics function
- [ ] Check carriage returns `\r` in import files (Windows), check with `dos2unix`
- [ ] Understand `date.tm_isdst` and `mktime` with imports between 23:00 and 01:00

### CODE REVIEW

**Comment by in0rdr** [comment]
Follow-up issue https://github.com/in0rdr/diary/issues/78 to tackle outstanding questions.

Still many memory issues, it needs more work, but works well enough for alpha testing @kristoferus75 (make sure to use a [tmp import diary directory](https://github.com/in0rdr/diary/blob/master/TESTING.md?plain=1#L9) to protect your prod data).

**Comment by kristoferus75** [comment]
Hi ! i have now test it with the new diary but after i press i and and again press a to import all from this ics file i see no entries in the calendar from the ics file hmmm
i use an extra other diary directory ...  

an example entry  from my vcalendar ics file :

```
BEGIN:VEVENT
UID:
 040000008200E00074C5B7101A82E008000000000043FC4198C1D701000000000000000010
 000000005C56D12F529A4C971C7AE883D6ECDF
DTSTAMP:00000000T000000
DTSTART:20211118T160000
DTEND:20211118T210000
DESCRIPTION:bla bla bla
SUMMARY:TEST 2021
SEQUENCE:0
CLASS:PUBLIC
TRANSP:OPAQUE
LOCATION:TEST\, 6666
 ORT
STATUS:CONFIRMED
CREATED:00000000T000000
LAST-MODIFIED:00000000T000000
ORGANIZER:MAILTO:test11111@test.at
ATTENDEE;ROLE=REQ-PARTICIPANT;RSVP=TRUE;CUTYPE=INDIVIDUAL;
 PARTSTAT=NEEDS-ACTION:test01@test.at
ATTENDEE;ROLE=REQ-PARTICIPANT;RSVP=TRUE;CUTYPE=INDIVIDUAL;
 PARTSTAT=NEEDS-ACTION:test02@test.at
ATTENDEE;ROLE=REQ-PARTICIPANT;RSVP=TRUE;CUTYPE=INDIVIDUAL;
 PARTSTAT=NEEDS-ACTION:test03@test.at
ATTENDEE;ROLE=REQ-PARTICIPANT;RSVP=TRUE;CUTYPE=INDIVIDUAL;
 PARTSTAT=ACCEPTED:test04@test.at
END:VEVENT
```

**Comment by kristoferus75** [comment]
Hi !

perhaps this helps:

with only one entry in an ics it works !! 

regards
kristoferus

**Comment by in0rdr** [comment]
Thanks a lot for testing @kristoferus75. I only tested with one `VEVENT` for the last few iterations. I pushed a commit to stop and actually handle the `VEVENT` entry just now in https://github.com/in0rdr/diary/commit/1e74922dd9816733354d3ac990a4fd8372fbb0f7. Hope that helps.

However, I noticed that the `DESCRIPTION` fields are not unfolded properly yet. Most of the entries look a bit too short, so I'll have to look further into that. I guess it has something to do with how line endings are handled.

Then there is another issue, where the current cursor date is off by -1 day after the import. This depends a bit on the time (24h) when you do the import. I have not found out yet why it behaves this way, but it might have something to do with DST (`tm.tm_isdst`). We just had the change in DST (winter time here now, and I once again totally forgot about the change :laughing:).

I made a note on few of these things in https://github.com/in0rdr/diary/issues/78 to continue working on this, but it clearly needs more work.

**Pull request merged**
