### PR TITLE
State and constness

### PR DESCRIPTION
**Pull request by matthiasbeyer**
Hi.

So this is a _proposal_. Every commit _could_ be applied individually, if you don't agree with some of the changes. I would also split it up into several PRs if you want me to.

What it does:

* Kill global state variables. We can pass around state in a `struct app_state` and simply pass around the pointer to it. It could even be enhanced and allocated on the stack instead of the heap, if you want me to fix this, tell me.
* Remove `is_leap` and replace it by a macro
* Add a `#define' for the date format string
* Add `const` whereever possible

---

**PLEASE** test this before merging. I did _not_ test this, although I compiled it.

### CODE REVIEW

**Comment by in0rdr** [comment]
Thank you very much for this contribution!

I looked at all the commits indidually and it looks very clean to me!! Good job in splitting up the commits. I think I will merge this 'as is' after testing. But first I want to fix the "pointer passing bug" mentioned [here](https://github.com/in0rdr/diary/issues/20). Please bare with me..

Thanks a lot

**Comment by matthiasbeyer** [comment]
If you do wish, I would push another commit to this PR where I move the state struct into the stack, so we do not have to use `malloc`/`free`!

**Comment by in0rdr** [comment]
I am trying to merge now, but [70838ab](https://github.com/in0rdr/diary/pull/22/commits/70838abe942dedc20f50cab1efe11491b91906a7) leaves me with a blank/white terminal, where the cursor can be moved but the dates are not visible.

I will look into it..

**Comment by in0rdr** [comment]
Only 	`70838ab` and `	3b4f53a` ('state' struct) are giving me trouble now.
The rest is merged and works fine, thank you.

**Pull request closed without merging**
