### PR TITLE
Improving layout of journal text to make it more readable

### PR DESCRIPTION
**Pull request by ryanbahneman**
With only 1 space between the calendar and the text it was a little inconvenient to read. I added 3 more spaces between the and text and calendar, as well as one more space between the date and the calendar.

### CODE REVIEW

**Comment by ryanbahneman** [comment]
Last commit should say "improving comments"

**Comment by in0rdr** [comment]
Amazing, thank you so much! Give me some time to merge the changes.

I like your `date_has_entry` implementation a lot, it is much more efficient than my [first try](https://github.com/in0rdr/diary/commit/1c991dd32773dc5e97bc7f1b1de25fa8d0ba126b#diff-d069a021cc8e9ad790c146d8e15b7e98R36)

**Comment by ryanbahneman** [comment]
Thanks!

I went a bit crazy on the changes, and I could have done a better job splitting out the code.

It's a very cool project you've started up. Good luck!

**Comment by in0rdr** [comment]
I merged your changes, but not all of them. In general I really loved your suggestions, also the distinction between today=UNDERLINE and has_entry=BOLD fits nicely. Especially the handling of the flags I found tricky, when to use `wchgat` and when to use `attron/attroff`. I was not aware you could just AND/OR them together like this, very cool!

> With only 1 space between the calendar and the text it was a little inconvenient to read

This is indeed true, but I like to have as much space as possible for actual content (not for spacing)

> Show maximum history

Very nice, I like this! I was not aware that most people read their past diary entries.

> Passing around the date and dir so that the functions are more general.

Also a very good suggestion. I kept this and made the function as general os possible, so that any date can be passed.

For highlighting the current date I chose to just mark it once at the end of the first diary drawing step, because at initialisation the current date will be found anyway. So no need to check it in the loop for every date.

Thank you so much for your help!!

**Comment by ryanbahneman** [comment]
Thanks for merging them in!

>  I was not aware you could just AND/OR them together like this, very cool!

Thanks, that's a trick I learned working with microcontrollers. It's a super common method for modifying a few bits in a register while leaving the rest of the state alone.

> I was not aware that most people read their past diary entries.

Yeah, I don't ready my past entries that often, but I like seeing the previous entries.

> So no need to check it in the loop for every date.

Good catch!

> This is indeed true, but I like to have as much space as possible for actual content (not for spacing)

Perhaps we can add something here like "|" to make the border more visible, or increase the width to 2 spaces instead of 4.

Anyway, Great work!

**Pull request closed without merging**
